sets.exported={
    main="Oatixur",
    ammo="Ginsen",
    head="Whirlpool Mask",
    body="Ken. Samue +1",
    hands="Hizamaru Kote +2",
    legs="Ken. Hakama +1",
    feet="Hiza. Sune-Ate +2",
    neck="Moonbeam Nodowa",
    waist="Black Belt",
    left_ear="Sherida Earring",
    right_ear="Reraise Earring",
    left_ring="Epona's Ring",
    right_ring="Regal Ring",
    back={ name="Segomo's Mantle", augments={'STR+20','Accuracy+20 Attack+20','"Dbl.Atk."+10',}},
}