sets.exported={
    main="Amanomurakumo",
    sub="Bloodrain Strap",
    range="Yoichinoyumi",
    ammo="Yoichi's Arrow",
    head="Flam. Zucchetto +2",
    body="Kasuga Domaru +1",
    hands="Wakido Kote +3",
    legs="Flamma Dirs +2",
    feet="Danzo Sune-Ate",
    neck={ name="Sam. Nodowa +1", augments={'Path: A',}},
    waist="Ioskeha Belt +1",
    left_ear="Telos Earring",
    right_ear="Cessance Earring",
    left_ring="Flamma Ring",
    right_ring="Warp Ring",
    back={ name="Smertrios's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10','Phys. dmg. taken-10%',}},
}