sets.exported={
    main="Shining One",
    sub="Bloodrain Strap",
    ammo="Ginsen",
    head="Flam. Zucchetto +2",
    body="Kasuga Domaru +1",
    hands="Wakido Kote +3",
    legs="Ken. Hakama +1",
    feet="Danzo Sune-Ate",
    neck={ name="Sam. Nodowa +1", augments={'Path: A',}},
    waist="Ioskeha Belt +1",
    left_ear="Telos Earring",
    right_ear="Cessance Earring",
    left_ring="Flamma Ring",
    right_ring="Karieyh Ring",
    back={ name="Smertrios's Mantle", augments={'AGI+20','Rng.Acc.+10 Rng.Atk.+10','Rng.Acc.+10','Weapon skill damage +10%',}},
}