sets.exported={
    main="Godhands",
    ammo="Staunch Tathlum +1",
    head="Whirlpool Mask",
    body="Ken. Samue +1",
    hands="Hizamaru Kote +2",
    legs="Ken. Hakama +1",
    feet="Hiza. Sune-Ate +2",
    neck="Loricate Torque +1",
    waist="Black Belt",
    left_ear="Genmei Earring",
    right_ear="Odnowa Earring +1",
    left_ring="Defending Ring",
    right_ring="Gelatinous Ring +1",
    back={ name="Segomo's Mantle", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+10','"Dbl.Atk."+10','Damage taken-5%',}},
}