sets.exported={
    main="Daybreak",
    sub={ name="Genbu's Shield", augments={'"Cure" potency +3%','Mag. Acc.+5','HP+24',}},
    range={ name="Dunna", augments={'MP+20','Mag. Acc.+10','"Fast Cast"+3',}},
    head="Azimuth Hood +1",
    body="Jhakri Robe +1",
    hands="Geo. Mitaines +1",
    legs={ name="Bagua Pants +1", augments={'Enhances "Mending Halation" effect',}},
    feet={ name="Bagua Sandals +1", augments={'Enhances "Radial Arcana" effect',}},
    neck="Twilight Torque",
    waist="Isa Belt",
    left_ear="Malignance Earring",
    right_ear="Colossus's Earring",
    left_ring={ name="Dark Ring", augments={'Enemy crit. hit rate -2','Magic dmg. taken -5%','Phys. dmg. taken -5%',}},
    right_ring={ name="Dark Ring", augments={'Breath dmg. taken -4%','Phys. dmg. taken -5%',}},
    back={ name="Lifestream Cape", augments={'Geomancy Skill +9','Indi. eff. dur. +19','Pet: Damage taken -4%','Damage taken-4%',}},
}