sets.exported={
    main={ name="Kali", augments={'Mag. Acc.+15','String instrument skill +10','Wind instrument skill +10',}},
    sub={ name="Kali", augments={'MP+60','Mag. Acc.+20','"Refresh"+1',}},
    range="Gjallarhorn",
    head="Aya. Zucchetto +1",
    body="Ayanmo Corazza +2",
    hands="Aya. Manopolas +1",
    legs="Aya. Cosciales +2",
    feet="Fili Cothurnes +1",
    neck="Twilight Torque",
    waist="Flume Belt +1",
    left_ear="Colossus's Earring",
    right_ear="Cassie Earring",
    left_ring={ name="Dark Ring", augments={'Enemy crit. hit rate -2','Magic dmg. taken -5%','Phys. dmg. taken -5%',}},
    right_ring="Gelatinous Ring +1",
    back="Moonbeam Cape",
}