sets.exported={
    main="Amanomurakumo",
    sub="Bloodrain Strap",
    ammo="Knobkierrie",
    head={ name="Valorous Mask", augments={'Attack+26','Weapon skill damage +3%','STR+15','Accuracy+13',}},
    body={ name="Sakonji Domaru +3", augments={'Enhances "Overwhelm" effect',}},
    hands={ name="Valorous Mitts", augments={'Accuracy+25 Attack+25','Weapon skill damage +2%','STR+8','Accuracy+10','Attack+10',}},
    legs="Wakido Haidate +2",
    feet="Hiza. Sune-Ate +2",
    neck="Fotia Gorget",
    waist="Fotia Belt",
    left_ear={ name="Moonshade Earring", augments={'Attack+4','TP Bonus +250',}},
    right_ear="Thrud Earring",
    left_ring="Regal Ring",
    right_ring="Karieyh Ring",
    back={ name="Smertrios's Mantle", augments={'STR+20','Accuracy+20 Attack+20','STR+10','Weapon skill damage +10%',}},
}